apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
spec:
  destination:
    name: argo-prod
    namespace: default
    server: ''
  source:
    path: guestbook
    repoURL: 'https://github.com/argoproj/argocd-example-apps/'
    targetRevision: HEAD
  sources: []
  project: default
